apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-1
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: Deployment
    name: deployment-1
  targetCPUUtilizationPercentage: 75
status:
  currentReplicas: 5
  desiredReplicas: 0
