apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-1
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-1
  targetCPUUtilizationPercentage: 1
