apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: deployment-1
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-1
  updatePolicy:
    updateMode: "Off"
