apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-plain
spec:
  host: {{ .Release.Name }}-plain.{{ .Values.domain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
