kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.default: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Release.Name }}-route-reencrypt"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.ingress: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Release.Name }}-ingress-reencrypt"}}'
  name: {{ .Release.Name }}
