apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: default
spec:
  data:
  - remoteRef:
      key: openshift/testsecret
      property: password
    secretKey: testsecret
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: example-sync
