apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: openshift
          serviceAccountRef:
            name: vault-auth
            namespace: default
      path: kv
      server: https://vault01.example.com:8200/
      version: v2
