apiVersion: v1
kind: Service
metadata:
  name: deployment-1-external
spec:
  externalIPs:
  - 192.168.1.193
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
