apiVersion: v1
kind: Service
metadata:
  name: deployment-1-lb
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
  selector:
    app: deployment-1
  type: LoadBalancer
