apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  destination:
    namespace: argocd-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment/test-chart
    repoURL: https://github.com/slauger/openshift-training-snippets
    targetRevision: master
  syncPolicy: {}
